export const SET_BTN_LOADING = "SET_BTN_LOADING";

export const SET_PAGE_LOADING = "SET_PAGE_LOADING";

export const SET_POPUP_ACTIONS = "SET_POPUP_ACTIONS";

export const SET_HEADER = "SET_HEADER";

export const SET_SIGNED_UP_MAIL = "SET_SIGNED_UP_MAIL";

export const SET_LOGIN_DATA = "SET_LOGIN_DATA";

export const SET_LOGIN_STATE = "SET_LOGIN_STATE";

export const SET_FORGOT_PASSWORD_MAIL = "SET_FORGOT_PASSWORD_MAIL";

export const SET_ALL_CATEGORIES_DATA = "SET_ALL_CATEGORIES_DATA";

export const SET_ALL_SUBCATEGORIES_DATA = "SET_ALL_SUBCATEGORIES_DATA";

export const SET_SUBCATEGORIES_DATA = "SET_SUBCATEGORIES_DATA";

export const SET_SINGLE_PRODUCT_DATA = "SET_SINGLE_PRODUCT_DATA";

export const SET_MY_CART_DATA = "SET_MY_CART_DATA";

export const SET_CART_ITEMS = "SET_CART_ITEMS";

export const SET_CART_PAYMENTS = "SET_CART_PAYMENTS";

export const SET_MY_ADD_TO_CART = "SET_MY_ADD_TO_CART";

export const SET_DELETE_MY_CART_ITEM = "SET_DELETE_MY_CART_ITEM";

export const SET_ADD_REMOVE_WISHLIST = "SET_ADD_REMOVE_WISHLIST";

export const SET_USER_PROFILE_DATA = "SET_USER_PROFILE_DATA";

export const SET_WISHLIST_DATA = "SET_WISHLIST_DATA";

export const SET_UPDATE_MY_CART = "SET_UPDATE_MY_CART";

export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";

export const SET_HOME_PAGE_DATA = "SET_HOME_PAGE_DATA";

export const SET_ADD_NEW_ADDRESS = "SET_ADD_NEW_ADDRESS";

export const SET_ADDRESS_LIST = "SET_ADDRESS_LIST";

export const SET_EDIT_MY_ADDRESS = "SET_EDIT_MY_ADDRESS";

export const SET_REMOVE_MY_ADDRESS = "SET_REMOVE_MY_ADDRESS";

export const SET_ALL_ORDERS_LIST = "SET_ALL_ORDERS_LIST";

export const SET_LOCATION_BY_SEARCH = "SET_LOCATION_BY_SEARCH";

export const SET_MY_CURRENT_DEFAULT_ADDRESS = "SET_MY_CURRENT_DEFAULT_ADDRESS";

export const SET_MY_ORDER = "SET_MY_ORDER";

export const SET_MY_ORDER_DETALS = "SET_MY_ORDER_DETALS";

export const SET_UPDATE_MY_PROFILE_DATA = "SET_UPDATE_MY_PROFILE_DATA";

export const SET_CONTACT_US = "SET_CONTACT_US";

export const SET_CANCEL_MY_ORDER = "SET_CANCEL_MY_ORDER";

export const SET_RE_ORDER = "SET_RE_ORDER";

export const SET_SEARCH_LIST = "SET_SEARCH_LIST";

export const SET_FAQ_SEARCH_LIST = "SET_FAQ_SEARCH_LIST";

export const SET_PRODUCTS_LIST = "SET_PRODUCTS_LIST";

export const SET_REQUEST_REASON = "SET_REQUEST_REASON";

export const SET_CREATE_TICKET = "SET_CREATE_TICKET";

export const SET_TICKET_DETAILS = "SET_TICKET_DETAILS";

export const SET_CONTECTUS_REASONS_DETAILS = "SET_CONTECTUS_REASONS_DETAILS";

export const SET_DISTRIBUTER_REGISTER = "SET_DISTRIBUTER_REGISTER";

export const SET_MY_CHAT_LIST = "SET_MY_CHAT_LIST";

export const SET_MY_PRESENT_MESSAGE = "SET_MY_PRESENT_MESSAGE";

export const SET_USERS_COMMENTES = "SET_USERS_COMMENTES";

export const SET_REMOVE_COUPON = "SET_REMOVE_COUPON";

export const SET_APPLY_COUPON = "SET_APPLY_COUPON";

export const SET_MY_PAGE_DATA = "SET_MY_PAGE_DATA";

export const SET_MY_TEAM = "SET_MY_TEAM";

export const SET_TEMSOF_USE = "SET_TEMSOF_USE";

export const SET_THIS_MY_PERMANENT_DEFAULT_ADDRESS =
  "SET_THIS_MY_PERMANENT_DEFAULT_ADDRESS";

export const SET_PRIVACY_POLICY = "SET_PRIVACY_POLICY";

export const SET_ASK_US_ANYTHING = "SET_ASK_US_ANYTHING";

export const SET_CART_ITEMS_IN_LOCALSTORAGE = "SET_CART_ITEMS_IN_LOCALSTORAGE";

export const SET_FOOTER_ADDRESS = "SET_FOOTER_ADDRESS";
